[package]
name = "posixutils-sh"
version = "0.7.0"
edition = "2021"

[dependencies]
gettext-rs.workspace = true
libc.workspace = true
plib = { path = "../plib" }

[dev-dependencies]
plib = { path = "../plib" }

[[bin]]
name = "sh"
path = "main.rs"
