[package]
name = "posixutils-sh"
version = "0.1.7"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
gettext-rs.workspace = true
nix = { version = "0.29", features = ["process", "fs", "resource", "signal", "user", "term"] }
atty.workspace = true

[[bin]]
name = "sh"
path = "src/main.rs"
