[package]
name = "posixutils-file"
version = "0.1.4"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
libc = "0.2"

[[bin]]
name = "cat"
path = "src/cat.rs"

[[bin]]
name = "cp"
path = "src/cp.rs"

[[bin]]
name = "dd"
path = "src/dd.rs"

[[bin]]
name = "split"
path = "src/split.rs"

[[bin]]
name = "tee"
path = "src/tee.rs"

