[package]
name = "posixutils-datetime"
version = "0.1.3"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
chrono = "0.4"

[[bin]]
name = "cal"
path = "src/cal.rs"

[[bin]]
name = "sleep"
path = "src/sleep.rs"

