[package]
name = "posixutils-datetime"
version = "0.1.6"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
gettext-rs.workspace = true
chrono = "0.4"
libc.workspace = true

[[bin]]
name = "cal"
path = "src/cal.rs"

[[bin]]
name = "date"
path = "src/date.rs"

[[bin]]
name = "sleep"
path = "src/sleep.rs"

