[package]
name = "posixutils-tree"
version = "0.1.5"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
walkdir = "2.5"
libc = "0.2"
chrono = "0.4"

[[bin]]
name = "chgrp"
path = "src/chgrp.rs"

[[bin]]
name = "chmod"
path = "src/chmod.rs"

[[bin]]
name = "chown"
path = "src/chown.rs"

[[bin]]
name = "du"
path = "src/du.rs"

[[bin]]
name = "link"
path = "src/link.rs"

[[bin]]
name = "ln"
path = "src/ln.rs"

[[bin]]
name = "mkfifo"
path = "src/mkfifo.rs"

[[bin]]
name = "mv"
path = "src/mv.rs"

[[bin]]
name = "rm"
path = "src/rm.rs"

[[bin]]
name = "rmdir"
path = "src/rmdir.rs"

[[bin]]
name = "touch"
path = "src/touch.rs"

[[bin]]
name = "unlink"
path = "src/unlink.rs"

