[package]
name = "posixutils-tree"
version = "0.1.12"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
gettext-rs.workspace = true
libc.workspace = true
regex.workspace = true
chrono.workspace = true
atty.workspace = true

[features]
posixutils_test_all = []
requires_root = []

[[bin]]
name = "chgrp"
path = "src/chgrp.rs"

[[bin]]
name = "chmod"
path = "src/chmod.rs"

[[bin]]
name = "chown"
path = "src/chown.rs"

[[bin]]
name = "cp"
path = "src/cp.rs"

[[bin]]
name = "du"
path = "src/du.rs"

[[bin]]
name = "link"
path = "src/link.rs"

[[bin]]
name = "ln"
path = "src/ln.rs"

[[bin]]
name = "ls"
path = "src/ls.rs"

[[bin]]
name = "mkdir"
path = "src/mkdir.rs"

[[bin]]
name = "mkfifo"
path = "src/mkfifo.rs"

[[bin]]
name = "mv"
path = "src/mv.rs"

[[bin]]
name = "readlink"
path = "src/readlink.rs"

[[bin]]
name = "rm"
path = "src/rm.rs"

[[bin]]
name = "rmdir"
path = "src/rmdir.rs"

[[bin]]
name = "touch"
path = "src/touch.rs"

[[bin]]
name = "unlink"
path = "src/unlink.rs"

