[package]
name = "posixutils-pathnames"
version = "0.1.2"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }

[[bin]]
name = "basename"
path = "src/basename.rs"

[[bin]]
name = "dirname"
path = "src/dirname.rs"

