[package]
name = "posixutils-pathnames"
version = "0.1.5"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
gettext-rs.workspace = true
libc.workspace = true

[[bin]]
name = "basename"
path = "src/basename.rs"

[[bin]]
name = "dirname"
path = "src/dirname.rs"

[[bin]]
name = "pathchk"
path = "src/pathchk.rs"

