[package]
name = "posixutils-xform"
version = "0.7.0"
authors = ["Jeff Garzik"]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
libc.workspace = true
gettext-rs.workspace = true
base64 = "0"
flate2 = "1"

[lints]
workspace = true

[[bin]]
name = "cksum"
path = "./cksum.rs"

[[bin]]
name = "compress"
path = "./compress.rs"

[[bin]]
name = "uudecode"
path = "./uudecode.rs"

[[bin]]
name = "uuencode"
path = "./uuencode.rs"
