[package]
name = "posixutils-xform"
version = "0.1.7"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
gettext-rs.workspace = true
uuencode = "0.1"
base64 = "0.21"

[[bin]]
name = "cksum"
path = "src/cksum.rs"

[[bin]]
name = "uncompress"
path = "src/uncompress.rs"

[[bin]]
name = "uudecode"
path = "src/uudecode.rs"

[[bin]]
name = "uuencode"
path = "src/uuencode.rs"

