[package]
name = "posixutils-awk"
version = "0.1.7"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
gettext-rs.workspace = true
clap.workspace = true
libc.workspace = true
pest = "2.7.10"
pest_derive = "2.7.10"
lazy_static = "1.4.0"
lexical = { version = "6.1", features = ["format"] }
rand = {version = "0.8.5", no-default-features = false, features = ["small_rng"] }

[[bin]]
name = "awk"
path = "src/main.rs"
